---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-business-data-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dq-business-data-manager
    spec:
      containers:
      - name: dq-business-data-manager
        image: quay.io/ukhomeofficedigital/business-data-manager:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        env:
          - name: ENV
            value: 'dev'
          - name: LOG_LEVEL
            value: 'info'
          - name: NAME
            value: 'business-data-manager'
          - name: PORT
            value: '8080'
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: bdm
                key: sessionsecret
          - name: TITLE
            value: 'Business Data Manager'
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: dq-apps-notprod-postgres-rds
                key: endpoint
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: dq-apps-notprod-postgres-rds
                key: port
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: dq-apps-notprod-postgres-rds
                key: username
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: dq-apps-notprod-postgres-rds
                key: database_name
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: dq-apps-notprod-postgres-rds
                key: password
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_CLIENT_ID
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_CLIENT_SECRET
          - name: PROXY_LISTEN
            value: 0.0.0.0:8081
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_DISCOVERY
          - name: PROXY_UPSTREAM_URL
            value: http://127.0.0.1:8080
        args:
          - --resources
          - uri=/*|roles=bdm
          - --enable-logging
          - --enable-json-logging
          - --verbose
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
