---
apiVersion: v1
kind: Secret
metadata:
  name: dq-apps-bdm-staging-rds
type: Opaque
data:
  endpoint: {{.PGHOST}}
  port: {{.PGPORT}}
  username: {{.PGUSER}}
  db_name: {{.PGDATABASE}}
  password: {{.PGPASSWORD}}
