---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dq-business-data-manager-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-external"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: dq-business-data-manager-service
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{.HOSTNAME}}
    secretName: business-data-manager-tls-cmio
