---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dq-business-data-manager-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "false"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-external"
    kubernetes.io/tls-acme: "true"
#    ingress.kubernetes.io/server-snippet: |
#      proxy_buffer_size             256k;
#      proxy_buffers                 4 256k;
#      large_client_header_buffers   4 32k;
spec:
  rules:
  - host: {{.HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: dq-business-data-manager-service
          servicePort: keycloak
        path: /
  tls:
  - hosts:
    - {{.HOSTNAME}}
    secretName: business-data-manager-tls-cmio
