apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-bdm
spec:
  podSelector:
    matchLabels:
      name: dq-business-data-manager
  ingress:
    - ports:
      - protocol: TCP
        port: 10443
