---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dq-business-data-manager-service
  name: dq-business-data-manager-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: dq-business-data-manager
