---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dq-business-data-manager-service
  name: dq-business-data-manager-service
spec:
  ports:
  - name: keycloak
    port: 443
    targetPort: keycloak
  - name: dq-business-data-manager
    port: {{ .WEB_PORT }}
    targetPort: {{ .WEB_PORT }}
  selector:
    name: dq-business-data-manager
